version: "3"
services:
  haproxy:
    image: haproxy:2.6
    volumes:
      - ./haproxy:/haproxy-override
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "8000:80"
      - "8001:70"
