version: "3"

services:
  redis:
    image: "bitnami/redis:7.0"
    environment:
      - REDIS_PASSWORD=password123
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/bitnami/redis/data"